insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (1, 'Photobean', 'Research and Development', 'Yosef Yeshua', '052-976-5022');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (2, 'Gabspot', 'Training', 'Netanel Hassid', '055-345-9073');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (3, 'Twitterlist', 'Support', 'Alexina Sorel', '941-458-0624');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (4, 'Flashspan', 'Human Resources', 'Oralee Faccini', '472-733-7635');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (5, 'Quimba', 'Training', 'Auberon Aupol', '432-697-0780');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (6, 'Kwimbee', 'Services', 'Elsey Reany', '955-641-2336');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (7, 'Skibox', 'Product Management', 'Janina Rayner', '403-502-0955');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (8, 'Jaxbean', 'Human Resources', 'Cordi Foden', '973-162-7186');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (9, 'Skalith', 'Support', 'Nancie Balogun', '265-696-2395');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (10, 'Ntag', 'Research and Development', 'Frieda Mallaby', '295-635-9569');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (11, 'Roomm', 'Support', 'Alyse Quantrill', '667-381-5745');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (12, 'Feedfire', 'Engineering', 'Sonnie Gehrtz', '535-206-7883');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (13, 'Cogidoo', 'Marketing', 'Miguelita Jeffery', '104-620-2933');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (14, 'Youbridge', 'Marketing', 'Allix Grundwater', '694-605-9419');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (15, 'Jabberbean', 'Legal', 'Linet Alsopp', '985-487-2538');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (16, 'Divanoodle', 'Legal', 'Meriel Reape', '932-189-7466');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (17, 'Leenti', 'Training', 'Elsy Bolesma', '573-867-0701');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (18, 'Flashdog', 'Marketing', 'Bernice Nobriga', '128-814-9774');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (19, 'Yadel', 'Services', 'Wallache Meharry', '406-930-0857');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (20, 'Vitz', 'Accounting', 'Skyler Ramsby', '257-944-6434');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (21, 'Skimia', 'Accounting', 'Pam Dionisio', '779-723-3938');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (22, 'Viva', 'Research and Development', 'Cobby Sautter', '278-234-4498');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (23, 'Mybuzz', 'Services', 'Parke Tunnacliffe', '803-647-4752');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (24, 'Trilia', 'Product Management', 'Borg Ferier', '996-493-1820');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (25, 'Centizu', 'Accounting', 'Lowrance Scinelli', '312-819-8375');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (26, 'Flashset', 'Sales', 'Peadar Fradgley', '801-964-1244');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (27, 'Dabfeed', 'Support', 'Way Fahey', '414-575-7749');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (28, 'Kwinu', 'Services', 'Holmes Chang', '182-623-8188');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (29, 'Vitz', 'Research and Development', 'Dania Kluss', '567-810-5222');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (30, 'Tazzy', 'Training', 'Nicolle Bardey', '518-349-1781');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (31, 'Centizu', 'Human Resources', 'Myles Galiero', '776-116-0577');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (32, 'Brainbox', 'Research and Development', 'Heinrik Henstridge', '778-937-5600');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (33, 'Flashpoint', 'Research and Development', 'Moyna Cholomin', '813-594-9549');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (34, 'Edgewire', 'Sales', 'Tressa Oertzen', '286-422-9845');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (35, 'Trunyx', 'Engineering', 'Tades Byfford', '779-843-6457');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (36, 'Wikido', 'Services', 'Tim Tefft', '795-703-6219');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (37, 'Katz', 'Business Development', 'Anni Bedborough', '146-963-8306');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (38, 'Linkbuzz', 'Legal', 'Sigvard Asquez', '473-256-5374');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (39, 'Tagchat', 'Research and Development', 'Fania Vondrak', '104-952-1474');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (40, 'Rooxo', 'Legal', 'Beatrix Theuss', '133-542-7589');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (41, 'Jetpulse', 'Sales', 'Anatole Thibodeaux', '225-629-0251');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (42, 'Feednation', 'Sales', 'Norbert Shingfield', '952-843-6382');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (43, 'Skynoodle', 'Research and Development', 'Alric Rich', '320-353-1896');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (44, 'Browsetype', 'Legal', 'Joyous Kamienski', '240-885-1089');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (45, 'Gabspot', 'Services', 'Hermine Bevar', '706-104-1290');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (46, 'Voomm', 'Support', 'Rriocard Le Hucquet', '496-223-3028');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (47, 'Yodo', 'Marketing', 'Valery Harmeston', '555-375-5961');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (48, 'Gevee', 'Human Resources', 'Tiffi Gredden', '207-777-8782');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (49, 'Yombu', 'Business Development', 'Jervis Stovell', '177-349-2855');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (50, 'Youbridge', 'Training', 'Karlis Vogele', '560-863-5405');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (51, 'Meezzy', 'Training', 'Richard Clulow', '927-884-1376');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (52, 'Aimbu', 'Sales', 'Ermengarde Balharry', '715-856-3099');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (53, 'Cogidoo', 'Legal', 'Lissi Droghan', '461-248-2411');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (54, 'Ozu', 'Accounting', 'Sonia Larner', '901-357-5868');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (55, 'Blogtag', 'Training', 'Kelvin Videler', '772-439-0688');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (56, 'Pixonyx', 'Product Management', 'Chiquia Gilroy', '300-815-7876');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (57, 'Viva', 'Services', 'Ingamar Meritt', '465-365-5573');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (58, 'Abata', 'Product Management', 'Montague Lukash', '745-109-0787');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (59, 'Fivespan', 'Legal', 'Neille Bickmore', '809-647-6319');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (60, 'Rhybox', 'Engineering', 'Marcie Cranham', '773-152-4928');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (61, 'Riffpath', 'Research and Development', 'Valeda Rawnsley', '104-875-2994');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (62, 'Jaxbean', 'Accounting', 'Angie Kensett', '170-724-5683');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (63, 'Devpoint', 'Sales', 'Lou Simoncello', '891-457-1164');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (64, 'Browsetype', 'Product Management', 'Sammie Rockwell', '471-569-0623');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (65, 'Edgewire', 'Sales', 'Marley Temblett', '911-441-7847');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (66, 'Skajo', 'Business Development', 'Stephenie Clew', '646-435-3497');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (67, 'Topicshots', 'Human Resources', 'Rochelle Bordes', '215-953-3841');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (68, 'Photofeed', 'Product Management', 'Adolph Meineken', '580-189-2230');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (69, 'Fadeo', 'Training', 'Galina Abbey', '985-229-1426');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (70, 'Meevee', 'Legal', 'Hamid Scopes', '352-461-9542');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (71, 'Zoozzy', 'Business Development', 'Lorilyn McGrorty', '262-361-5472');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (72, 'Tagcat', 'Training', 'Shirline Josifovic', '631-461-2858');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (73, 'Fadeo', 'Support', 'Aguie Peal', '237-672-8149');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (74, 'DabZ', 'Engineering', 'Dermot Berens', '177-482-0510');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (75, 'Brainsphere', 'Accounting', 'Edd Fairnie', '995-238-9852');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (76, 'Podcat', 'Human Resources', 'Laughton Hedge', '109-344-6288');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (77, 'Fadeo', 'Training', 'Willette Krysztofiak', '598-443-9844');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (78, 'Skaboo', 'Engineering', 'Godiva Dahlbom', '790-162-6944');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (79, 'Einti', 'Business Development', 'Oby Southby', '109-506-1302');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (80, 'Buzzbean', 'Support', 'Pietro Keems', '838-839-2543');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (81, 'Skimia', 'Sales', 'Alberta Humphrey', '449-496-0931');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (82, 'Babbleblab', 'Accounting', 'Johnette Wallice', '691-382-9088');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (83, 'Trilith', 'Support', 'Nikolos Tremmil', '227-795-0121');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (84, 'Zazio', 'Support', 'Sutherlan Brithman', '122-885-3417');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (85, 'Oyoyo', 'Product Management', 'Ofelia McCosker', '362-204-8302');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (86, 'Oyoba', 'Support', 'Cory Bende', '639-253-5788');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (87, 'Flipopia', 'Sales', 'Melanie Damato', '597-592-2946');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (88, 'Skinix', 'Marketing', 'Kimmie Thirlwell', '350-951-4849');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (89, 'Gigazoom', 'Legal', 'Page Branton', '606-457-7811');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (90, 'Centidel', 'Services', 'Yolande Srawley', '637-419-1186');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (91, 'Skimia', 'Human Resources', 'Devan Sulter', '684-650-8461');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (92, 'Oloo', 'Business Development', 'Donavon Paxforde', '631-594-8555');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (93, 'Trudeo', 'Human Resources', 'Findley Itzkovwich', '414-967-8709');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (94, 'Eadel', 'Engineering', 'Libbey Brame', '362-350-5697');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (95, 'Browsedrive', 'Business Development', 'Arleyne Chandler', '946-196-5442');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (96, 'Ooba', 'Support', 'Lalo Crownshaw', '143-763-4988');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (97, 'Wordify', 'Product Management', 'Zorana Lung', '334-205-8186');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (98, 'Yakijo', 'Support', 'Martie Jerrome', '435-779-3144');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (99, 'Leexo', 'Training', 'Lisette Beilby', '800-648-1528');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (100, 'Dynazzy', 'Business Development', 'Niki Brook', '109-530-7745');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (101, 'Agivu', 'Legal', 'Baird Jarnell', '562-138-3076');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (102, 'Mydeo', 'Research and Development', 'Lewiss Praundl', '244-373-4669');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (103, 'Omba', 'Human Resources', 'Debby Brinded', '952-687-7733');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (104, 'Babbleblab', 'Legal', 'Sigfried Van Hove', '603-954-2728');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (105, 'Eayo', 'Product Management', 'Valentin Ruslin', '974-614-3049');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (106, 'Blognation', 'Human Resources', 'Thorny Mallows', '998-102-9223');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (107, 'Yabox', 'Marketing', 'Linnet Birney', '879-191-9010');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (108, 'Midel', 'Human Resources', 'Henrik Crutcher', '257-433-1146');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (109, 'Youfeed', 'Services', 'Shauna Elkin', '677-386-9465');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (110, 'Youspan', 'Product Management', 'Marthena Fillan', '661-670-4133');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (111, 'Skinder', 'Product Management', 'Lexie L''Episcopi', '338-491-7805');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (112, 'Feedspan', 'Product Management', 'Ode Duerdin', '347-462-9065');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (113, 'Feedspan', 'Accounting', 'Rodney Goodwell', '204-404-1939');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (114, 'Lazzy', 'Sales', 'Kyrstin Stealey', '354-875-8995');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (115, 'Lazz', 'Human Resources', 'Annadiana Toope', '389-907-0279');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (116, 'Quimba', 'Marketing', 'Hedda St. John', '426-156-1189');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (117, 'Divavu', 'Support', 'Batholomew Ullock', '165-594-9490');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (118, 'Feedfish', 'Services', 'Nelli Alflat', '943-808-1176');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (119, 'Eidel', 'Product Management', 'Lou Tunnoch', '584-325-2686');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (120, 'Vimbo', 'Research and Development', 'Florencia Duke', '581-286-4456');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (121, 'Quimba', 'Research and Development', 'Langston Gullefant', '289-454-4900');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (122, 'Mynte', 'Business Development', 'Malory Danskine', '480-601-2010');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (123, 'Zava', 'Research and Development', 'Thea Dreghorn', '515-588-3864');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (124, 'Browsezoom', 'Human Resources', 'Estevan Kimbury', '921-718-0995');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (125, 'Viva', 'Sales', 'Perceval Santori', '752-429-8668');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (126, 'Babbleset', 'Legal', 'Nicoli Doone', '846-283-2595');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (127, 'Kayveo', 'Engineering', 'Dominica Dowse', '148-593-7959');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (128, 'Trupe', 'Research and Development', 'Letty Boagey', '517-923-7373');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (129, 'Twimbo', 'Marketing', 'Trstram Merrywether', '722-179-0763');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (130, 'Brainsphere', 'Accounting', 'Sasha MacGilpatrick', '452-867-7449');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (131, 'Oodoo', 'Support', 'Brannon Weblin', '212-181-4571');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (132, 'Bubbletube', 'Support', 'Antone Denyukin', '829-508-0645');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (133, 'Thoughtbeat', 'Engineering', 'Erminia Hobgen', '371-192-3449');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (134, 'Zoomdog', 'Engineering', 'Rosie Romayn', '995-911-2193');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (135, 'Tanoodle', 'Research and Development', 'Tracey Gravell', '664-214-8213');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (136, 'Avamm', 'Business Development', 'Page Harling', '653-396-8213');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (137, 'Zazio', 'Services', 'Ashley Vedstra', '393-423-0833');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (138, 'Rhyloo', 'Marketing', 'Brucie Gareisr', '755-290-2248');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (139, 'Zooxo', 'Legal', 'Faina Subhan', '931-688-1398');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (140, 'Dabjam', 'Training', 'Dwight Burbridge', '913-743-9984');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (141, 'Yodel', 'Services', 'Kellyann Brazenor', '896-248-1958');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (142, 'Topicware', 'Product Management', 'Sibby Carter', '494-381-4021');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (143, 'Demizz', 'Services', 'Marquita Devereu', '242-110-8368');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (144, 'Aivee', 'Product Management', 'Lucie Gowanson', '768-157-6074');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (145, 'Yotz', 'Marketing', 'Lisette Bontoft', '636-975-5272');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (146, 'Wordtune', 'Training', 'Sydney Michal', '811-658-4034');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (147, 'Kwinu', 'Marketing', 'Aluino Rollason', '809-180-1978');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (148, 'Dabjam', 'Business Development', 'Gerald Kildahl', '657-746-2797');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (149, 'Riffpedia', 'Support', 'Geralda Bartolomivis', '374-152-2906');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (150, 'Dabshots', 'Business Development', 'Christian Dunnet', '426-253-8954');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (151, 'Gabspot', 'Services', 'Leanna MacEllen', '486-890-1673');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (152, 'Youopia', 'Support', 'Lowell Klinck', '423-429-2340');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (153, 'Voomm', 'Marketing', 'Desmund Waddicor', '529-373-4004');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (154, 'Edgeblab', 'Human Resources', 'Vachel Andino', '499-398-0261');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (155, 'Dynazzy', 'Product Management', 'Tadd Gors', '657-790-0125');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (156, 'Devify', 'Accounting', 'Thomasin Wivell', '565-369-4864');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (157, 'Zooxo', 'Support', 'Phaedra Breeton', '475-291-2669');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (158, 'Avaveo', 'Training', 'Tades Stranaghan', '891-155-9636');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (159, 'Yabox', 'Services', 'Julianna Feltoe', '559-282-9499');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (160, 'Zoomlounge', 'Product Management', 'Guillaume Beldom', '692-171-8881');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (161, 'Zooveo', 'Engineering', 'Halsey Canon', '636-665-5297');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (162, 'Jaxworks', 'Research and Development', 'Loren Beament', '149-634-5804');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (163, 'Ozu', 'Support', 'Bertie Gifford', '749-562-8834');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (164, 'Skyndu', 'Services', 'Kile Spadeck', '310-249-1606');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (165, 'Browsebug', 'Support', 'Dorian Corkish', '533-832-7227');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (166, 'Kanoodle', 'Research and Development', 'Marijn McNiff', '502-184-5985');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (167, 'Twitternation', 'Support', 'Elbertina Baldree', '198-851-4078');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (168, 'Youtags', 'Research and Development', 'Peri Godfery', '761-322-5374');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (169, 'Fadeo', 'Support', 'Gavra Orry', '255-603-1431');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (170, 'Tagtune', 'Product Management', 'Walsh Robins', '205-901-9996');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (171, 'Browseblab', 'Sales', 'Angelina Etchingham', '923-400-5059');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (172, 'Kare', 'Business Development', 'Gretta Reynolds', '474-538-6944');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (173, 'Leenti', 'Support', 'Tedi Inkpin', '758-910-4015');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (174, 'Blognation', 'Marketing', 'Carly Cicchinelli', '354-557-7185');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (175, 'Roomm', 'Training', 'Phillip Raselles', '832-210-4242');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (176, 'Jabberbean', 'Marketing', 'Urbain Arundell', '687-851-7699');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (177, 'Quimba', 'Training', 'Laurella Schild', '263-671-5280');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (178, 'Leexo', 'Training', 'Anna-diana Veque', '749-435-1662');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (179, 'Tagopia', 'Engineering', 'Les Eskriett', '740-296-9882');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (180, 'Voolia', 'Support', 'Son Lumm', '652-591-1617');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (181, 'Vitz', 'Training', 'Guy Megarrell', '670-866-5042');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (182, 'Shuffletag', 'Legal', 'Velma Remon', '312-853-1042');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (183, 'Vitz', 'Product Management', 'Elwin Siveter', '895-135-7570');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (184, 'Topiczoom', 'Accounting', 'Willy Brunning', '343-375-4641');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (185, 'Rhycero', 'Support', 'Mab Murkus', '728-786-5514');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (186, 'Realfire', 'Marketing', 'Billie De Carlo', '601-970-4514');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (187, 'Skipstorm', 'Accounting', 'Ilysa Avrahamov', '525-652-1672');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (188, 'Skynoodle', 'Training', 'Sonnie Isson', '293-656-5052');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (189, 'Bubbletube', 'Human Resources', 'Audy Wallas', '856-779-2971');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (190, 'Centidel', 'Marketing', 'Albina Baggett', '902-422-1713');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (191, 'Trunyx', 'Sales', 'Davis Courtonne', '228-577-4952');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (192, 'Tagopia', 'Training', 'Brandice Frudd', '643-671-7239');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (193, 'Voonix', 'Training', 'Domenic Sweating', '946-898-7507');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (194, 'Tambee', 'Sales', 'Jeri Alessandone', '469-102-0274');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (195, 'Zoonoodle', 'Accounting', 'Grant Behne', '518-417-3852');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (196, 'Snaptags', 'Support', 'Silvain Sangster', '132-951-8767');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (197, 'Kamba', 'Human Resources', 'Heath Hallum', '675-835-7228');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (198, 'Meevee', 'Accounting', 'Neddy Harrowsmith', '717-371-1558');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (199, 'Thoughtmix', 'Training', 'Aubree Cisland', '839-434-3455');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (200, 'Skiptube', 'Support', 'Sandor Golden of Ireland', '442-315-4724');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (201, 'Brightbean', 'Sales', 'Tomi Proughten', '529-297-6925');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (202, 'Jaloo', 'Legal', 'Tobiah Andrejevic', '852-296-8316');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (203, 'Twimm', 'Marketing', 'Tallulah Strowger', '621-716-4972');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (204, 'Chatterpoint', 'Accounting', 'Tobe Steptoe', '980-678-5557');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (205, 'Jabbertype', 'Accounting', 'Noble McClintock', '211-676-1750');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (206, 'Twinte', 'Engineering', 'Orsola Biddulph', '125-561-0143');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (207, 'Babbleopia', 'Legal', 'Nicky Tremellier', '749-416-3009');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (208, 'Chatterpoint', 'Support', 'Iggy Tourner', '229-876-7035');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (209, 'Chatterpoint', 'Engineering', 'Merridie Isles', '361-331-1696');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (210, 'Browsezoom', 'Services', 'Marrilee Benley', '479-710-5162');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (211, 'Jabberstorm', 'Accounting', 'Veda Lindner', '656-813-1294');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (212, 'Buzzdog', 'Product Management', 'Simon Sappell', '145-977-3978');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (213, 'Youfeed', 'Training', 'Ruthanne Sergant', '797-848-7208');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (214, 'Abatz', 'Support', 'Odessa Camolli', '914-328-5055');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (215, 'Jaxnation', 'Sales', 'Cassandra McGrory', '463-825-7281');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (216, 'Jabbersphere', 'Engineering', 'Bria Heams', '528-309-5972');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (217, 'Miboo', 'Legal', 'Burgess Bowcock', '872-650-5119');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (218, 'Youfeed', 'Training', 'Carma Molesworth', '959-181-5892');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (219, 'Gevee', 'Accounting', 'Charles Bousfield', '748-443-9598');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (220, 'Oyoyo', 'Research and Development', 'Kaitlin Deathridge', '188-971-2598');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (221, 'Edgeblab', 'Support', 'Domingo Rollingson', '522-873-4375');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (222, 'Chatterpoint', 'Legal', 'Cindi Carnalan', '227-443-4830');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (223, 'Ntag', 'Human Resources', 'Ginelle Davley', '558-490-2389');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (224, 'Wordpedia', 'Accounting', 'Cary Guitonneau', '770-602-7671');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (225, 'Riffwire', 'Legal', 'Chery MacFie', '420-128-2591');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (226, 'Yabox', 'Marketing', 'Melva Antusch', '561-407-9083');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (227, 'Fatz', 'Business Development', 'Graig Yate', '773-844-8798');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (228, 'Jamia', 'Legal', 'Fidole Taffrey', '441-497-6610');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (229, 'Camimbo', 'Accounting', 'Elihu Cluitt', '915-913-0233');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (230, 'Jaloo', 'Business Development', 'Ximenes Carman', '139-382-5897');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (231, 'Wordtune', 'Research and Development', 'Tobie Bouttell', '698-456-0964');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (232, 'Topicware', 'Engineering', 'Margarete Bye', '871-708-1522');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (233, 'Mymm', 'Accounting', 'Aile Tiddy', '456-640-4238');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (234, 'Tazzy', 'Accounting', 'Torrance Lidster', '446-600-6928');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (235, 'Thoughtstorm', 'Services', 'Lurleen Gadsdon', '294-926-4751');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (236, 'Gabvine', 'Services', 'Mattie Meadus', '279-457-9933');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (237, 'Wordware', 'Legal', 'Lowell Stambridge', '116-921-4856');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (238, 'Babbleblab', 'Business Development', 'Lurline Calley', '127-483-4362');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (239, 'Browsetype', 'Services', 'Nariko Keyzor', '105-562-3785');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (240, 'Fliptune', 'Engineering', 'Katharine Ion', '764-713-9920');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (241, 'Riffpedia', 'Support', 'Keriann Antoni', '511-350-2912');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (242, 'Twitternation', 'Services', 'Twyla Hyndley', '788-750-3031');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (243, 'Meevee', 'Research and Development', 'Cindee McCooke', '196-409-5269');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (244, 'Riffwire', 'Sales', 'Caz McRoberts', '898-869-7700');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (245, 'Feedspan', 'Human Resources', 'Kettie Waiton', '107-899-9511');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (246, 'Aibox', 'Product Management', 'Nappy Kinmond', '987-676-9236');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (247, 'Brainbox', 'Training', 'Correy Kinchlea', '215-677-6656');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (248, 'Yoveo', 'Services', 'Willi Lathy', '479-750-1818');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (249, 'Aimbo', 'Product Management', 'Cobby Matskiv', '902-134-2643');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (250, 'Browsecat', 'Support', 'Eryn Boyde', '340-705-7911');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (251, 'Brainbox', 'Marketing', 'Zorana Seadon', '436-587-7072');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (252, 'Devbug', 'Services', 'Murry Scotsbrook', '249-306-3181');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (253, 'Latz', 'Training', 'Minnie Oxenbury', '387-354-9411');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (254, 'Aimbo', 'Training', 'Austin Nisius', '798-829-6743');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (255, 'Meejo', 'Business Development', 'Calida Juleff', '697-828-5204');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (256, 'Voomm', 'Engineering', 'Laverna Fleg', '235-144-4056');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (257, 'Devpoint', 'Services', 'Maribel Windibank', '345-971-3900');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (258, 'Realfire', 'Services', 'Jessy Coneau', '240-167-7774');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (259, 'Twimbo', 'Legal', 'Whit Dancer', '925-414-4631');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (260, 'Thoughtbeat', 'Human Resources', 'D''arcy Colls', '490-783-9866');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (261, 'Devpoint', 'Engineering', 'Tracey Vogeler', '952-501-2878');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (262, 'Omba', 'Services', 'Finlay Bettenay', '171-703-9652');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (263, 'Npath', 'Marketing', 'Ashlen Pocock', '820-762-6963');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (264, 'Browsecat', 'Legal', 'Nelli Beaves', '315-550-2877');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (265, 'Omba', 'Sales', 'Felix Kurth', '208-642-0662');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (266, 'Youspan', 'Training', 'Giffy Redwing', '389-796-4841');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (267, 'Zooxo', 'Services', 'Olivier Note', '459-802-8923');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (268, 'Brightbean', 'Services', 'Kassey Binge', '424-170-6456');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (269, 'Leenti', 'Sales', 'Karin Philott', '234-184-2781');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (270, 'Gigaclub', 'Marketing', 'Darius Jacklin', '380-368-0006');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (271, 'Buzzster', 'Business Development', 'Sylvia Heigold', '340-522-1731');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (272, 'Yata', 'Marketing', 'Gilberta Maudett', '672-183-2174');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (273, 'Quimm', 'Research and Development', 'Debera Jenicke', '247-171-4612');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (274, 'Zava', 'Marketing', 'Alaine Webborn', '703-804-7066');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (275, 'Centizu', 'Marketing', 'Minni Slany', '162-930-0887');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (276, 'Mymm', 'Legal', 'Perla Willison', '859-914-1812');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (277, 'Vidoo', 'Training', 'Annabel Ferrettino', '989-175-9183');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (278, 'Tagtune', 'Accounting', 'Yolanthe Dineges', '862-568-4652');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (279, 'Tagfeed', 'Accounting', 'Lory Sich', '541-141-2688');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (280, 'Thoughtmix', 'Training', 'Dal Kilmartin', '991-659-0850');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (281, 'Centidel', 'Training', 'Lamar Brooksbie', '142-633-2673');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (282, 'Mydo', 'Marketing', 'Lawry Ousbie', '937-373-7109');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (283, 'Mybuzz', 'Engineering', 'Joeann Amberger', '990-515-5316');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (284, 'Youspan', 'Human Resources', 'Amber Terrelly', '649-846-0414');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (285, 'Quatz', 'Services', 'Nonie Fruish', '603-517-4430');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (286, 'Aivee', 'Engineering', 'Nahum Dibnah', '656-152-7368');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (287, 'Tazz', 'Business Development', 'Leslie Mattam', '379-169-5682');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (288, 'Yotz', 'Product Management', 'Tymon Kettell', '957-259-1112');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (289, 'Skyndu', 'Research and Development', 'Myra MacKaig', '732-702-2587');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (290, 'Mymm', 'Engineering', 'Morry Paxforde', '880-526-0598');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (291, 'Zoombeat', 'Marketing', 'Fonsie Yard', '825-408-2682');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (292, 'Photospace', 'Research and Development', 'Cull O''Shields', '590-968-1931');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (293, 'Realbuzz', 'Training', 'Michale Rosendorf', '919-644-6611');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (294, 'Flashdog', 'Research and Development', 'Karil Winley', '777-406-4355');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (295, 'Quatz', 'Training', 'Ulysses Messenbird', '814-856-4217');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (296, 'Tagchat', 'Engineering', 'Myrwyn Stonuary', '419-157-5615');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (297, 'Flashdog', 'Legal', 'Jocko Laying', '155-663-4668');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (298, 'Eayo', 'Sales', 'Hoebart Ellissen', '581-517-6833');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (299, 'Wikizz', 'Engineering', 'Morna Dessaur', '369-484-3848');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (300, 'Devpoint', 'Business Development', 'Annice Boss', '380-981-2781');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (301, 'Gabvine', 'Product Management', 'Panchito Ahmed', '458-676-3867');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (302, 'Blogtags', 'Business Development', 'Jerrine Ashley', '422-667-3239');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (303, 'Wikizz', 'Services', 'Adelaida Springell', '517-140-9643');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (304, 'Flipbug', 'Research and Development', 'Hanni Renvoys', '625-260-3184');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (305, 'Quimm', 'Accounting', 'Cortie Ciobutaru', '236-221-6147');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (306, 'Browsecat', 'Research and Development', 'Viva Stuer', '613-846-7368');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (307, 'Brainverse', 'Marketing', 'Sylvan Pawellek', '497-110-4536');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (308, 'Blogpad', 'Support', 'Ashlin Camous', '466-445-7830');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (309, 'Meeveo', 'Human Resources', 'Wynn Hadigate', '290-960-9708');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (310, 'Eare', 'Legal', 'Wilton Clibbery', '874-776-3847');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (311, 'Fadeo', 'Human Resources', 'Stormi Randerson', '295-406-8113');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (312, 'DabZ', 'Product Management', 'Phillip Mertgen', '799-207-3324');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (313, 'Avamba', 'Marketing', 'Evan Juan', '989-640-5367');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (314, 'Brightbean', 'Training', 'Pascal Pluck', '755-507-6877');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (315, 'Devify', 'Support', 'Rafaellle Pahlsson', '839-168-8603');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (316, 'Omba', 'Human Resources', 'Alverta Cuzen', '961-753-1849');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (317, 'Plajo', 'Product Management', 'Krystle Burden', '994-382-6372');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (318, 'Youbridge', 'Training', 'Chastity Pettko', '483-572-7318');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (319, 'Vipe', 'Sales', 'Winne Cousens', '239-298-8703');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (320, 'Feedspan', 'Marketing', 'Willamina Eakins', '777-425-1129');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (321, 'Tagpad', 'Research and Development', 'Corly Plaister', '279-770-9784');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (322, 'Twiyo', 'Services', 'Amara Leve', '813-679-2151');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (323, 'Yotz', 'Product Management', 'Woodie Fried', '926-342-0063');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (324, 'Shuffletag', 'Support', 'Kelci Battle', '189-939-0333');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (325, 'Ozu', 'Services', 'Hannie Torbett', '209-562-9991');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (326, 'Zoonder', 'Legal', 'Garrik MacFadyen', '100-171-9417');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (327, 'Eare', 'Services', 'Ferrel Cawthra', '993-534-6532');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (328, 'Browseblab', 'Product Management', 'Sybil Whitchurch', '217-633-0047');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (329, 'Quimm', 'Research and Development', 'Moyra Othick', '435-233-5161');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (330, 'Myworks', 'Business Development', 'Beatriz Heffernan', '968-407-3428');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (331, 'Yacero', 'Accounting', 'Tanya Cail', '111-778-2037');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (332, 'Roodel', 'Sales', 'Erastus Proud', '510-855-7906');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (333, 'Oyoyo', 'Legal', 'Nancy Cuniffe', '147-437-0192');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (334, 'Abatz', 'Product Management', 'Tatiania Dunge', '208-715-0485');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (335, 'Yata', 'Product Management', 'Manolo Totton', '840-810-2650');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (336, 'Wikizz', 'Support', 'Clevey Shubotham', '713-418-1457');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (337, 'Feedmix', 'Research and Development', 'Jan Korb', '184-500-5554');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (338, 'Layo', 'Business Development', 'Devlin Dy', '198-825-9699');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (339, 'Vidoo', 'Marketing', 'Gregorius O''Toole', '165-535-8263');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (340, 'Topicstorm', 'Legal', 'Yancey Danilchenko', '867-936-2411');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (341, 'Quatz', 'Business Development', 'Paul D'' Angelo', '432-714-4847');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (342, 'Brightbean', 'Sales', 'Felike Fleeming', '988-414-5063');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (343, 'Vinte', 'Engineering', 'Pasquale De Cruz', '341-718-7648');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (344, 'Ooba', 'Product Management', 'Jesselyn Hartmann', '679-561-0573');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (345, 'Quimm', 'Marketing', 'Vivianne Eddicott', '833-732-2783');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (346, 'Thoughtstorm', 'Services', 'Rubin Hankard', '248-200-4936');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (347, 'Janyx', 'Marketing', 'Packston Dyson', '533-393-1552');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (348, 'Brightbean', 'Legal', 'Dunstan Idwal Evans', '227-474-8250');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (349, 'Wikivu', 'Support', 'Doloritas Crickmoor', '144-786-6819');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (350, 'Leenti', 'Product Management', 'Bert Breitler', '122-627-8108');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (351, 'Photojam', 'Support', 'Vivie Spittal', '326-638-2827');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (352, 'Quimba', 'Research and Development', 'Stacey Zellick', '106-537-7606');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (353, 'Jabbercube', 'Sales', 'Cosimo Jeffryes', '653-381-6997');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (354, 'Yakitri', 'Sales', 'Ric Haveline', '580-399-9904');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (355, 'Avamba', 'Services', 'Vladamir Jennison', '698-115-3432');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (356, 'Twinte', 'Human Resources', 'Laryssa Hammerich', '651-179-4031');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (357, 'Pixoboo', 'Human Resources', 'Ashlan Speirs', '949-595-5520');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (358, 'Youspan', 'Accounting', 'Trent Jimmes', '890-979-1137');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (359, 'Jayo', 'Services', 'Cristobal Beard', '652-481-3934');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (360, 'Geba', 'Support', 'Archer Bidnall', '599-276-6217');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (361, 'Tazz', 'Accounting', 'Noel Shillabeare', '494-483-4046');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (362, 'Kamba', 'Training', 'Eddie Chinnock', '252-167-3245');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (363, 'Npath', 'Marketing', 'Antonius Firth', '966-595-0015');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (364, 'Kaymbo', 'Product Management', 'Ilyssa Beincken', '178-429-7117');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (365, 'Leexo', 'Product Management', 'Candis Cordel', '790-407-6725');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (366, 'Miboo', 'Support', 'Bernardine Lomaz', '749-327-4855');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (367, 'Trudoo', 'Training', 'Noel Overil', '279-390-3276');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (368, 'Abata', 'Services', 'Myrvyn Dee', '466-571-8250');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (369, 'Tavu', 'Legal', 'Ginnie Minto', '824-120-3455');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (370, 'Yozio', 'Legal', 'Bevon Presidey', '798-100-1588');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (371, 'Twitterlist', 'Services', 'Alvera Whistan', '283-446-6559');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (372, 'Flipbug', 'Business Development', 'Taber Collier', '831-171-2038');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (373, 'Thoughtstorm', 'Research and Development', 'Stormie Baudou', '132-818-6965');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (374, 'Gabcube', 'Human Resources', 'Marshal Metcalf', '979-426-8990');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (375, 'Buzzbean', 'Support', 'Brendan Crowder', '490-864-9764');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (376, 'Eidel', 'Services', 'Cammy Buddington', '842-393-9839');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (377, 'Tagfeed', 'Sales', 'Ellen Hrachovec', '228-290-2225');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (378, 'Eabox', 'Training', 'Flint Sicely', '700-600-2757');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (379, 'Skimia', 'Services', 'Leesa Vasyutichev', '672-662-0839');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (380, 'Zoomlounge', 'Human Resources', 'Aviva Vasyutichev', '601-317-1446');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (381, 'Zoonder', 'Marketing', 'Janessa Clashe', '553-918-8039');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (382, 'Meezzy', 'Engineering', 'Mozes Poure', '298-375-5780');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (383, 'Muxo', 'Accounting', 'Barth Lineham', '693-941-1486');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (384, 'Yodo', 'Business Development', 'Natala Burfitt', '741-606-3655');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (385, 'Realcube', 'Product Management', 'Grady Huish', '271-514-4460');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (386, 'Oyope', 'Research and Development', 'Normie Punt', '636-291-9692');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (387, 'Quatz', 'Sales', 'Bryan Moylane', '915-604-9396');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (388, 'Skimia', 'Product Management', 'Sinclare Lerner', '313-436-5647');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (389, 'Ailane', 'Accounting', 'Patsy Daddow', '138-603-0022');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (390, 'Divape', 'Accounting', 'Jonie Dockrey', '814-149-1926');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (391, 'Jazzy', 'Sales', 'Edy Metcalfe', '976-677-8131');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (392, 'Oodoo', 'Product Management', 'Cari Varrow', '387-677-4003');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (393, 'Thoughtblab', 'Support', 'Helsa Kembrey', '396-682-2099');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (394, 'Yata', 'Legal', 'Bentley Fayers', '899-360-7382');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (395, 'Gigabox', 'Marketing', 'Mackenzie Drysdale', '141-974-1783');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (396, 'Quire', 'Sales', 'Annaliese Ferrie', '616-506-0235');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (397, 'Realbuzz', 'Accounting', 'Nichol Tanswill', '780-722-1373');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (398, 'Tazzy', 'Engineering', 'Aileen Goaley', '347-305-8783');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (399, 'Topiclounge', 'Legal', 'Otes Wratten', '637-691-7094');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (400, 'Quatz', 'Marketing', 'Jules Pennock', '845-541-8604');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (401, 'Teklist', 'Engineering', 'Justinian Todarello', '187-883-3695');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (402, 'Cogidoo', 'Marketing', 'Edi Delbergue', '717-395-5567');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (403, 'Flashspan', 'Support', 'Orlando Ballston', '877-558-9662');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (404, 'Bluejam', 'Engineering', 'Ana Bernot', '573-845-8993');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (405, 'Shufflebeat', 'Engineering', 'Dick Houlston', '172-849-1878');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (406, 'Yakitri', 'Legal', 'Isaac Haddock', '637-351-1682');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (407, 'Youopia', 'Training', 'Clarice Springtorpe', '339-668-0476');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (408, 'Meeveo', 'Training', 'Dane Dreger', '601-290-2420');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (409, 'Chatterpoint', 'Engineering', 'Umeko Botterell', '487-235-6074');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (410, 'Livetube', 'Research and Development', 'Pascale Raper', '654-127-2767');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (411, 'Blogtag', 'Accounting', 'Waiter Fernely', '831-946-3167');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (412, 'Twitternation', 'Support', 'Allan Dunsleve', '120-794-8112');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (413, 'Wordify', 'Training', 'Claudio Volet', '665-759-8119');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (414, 'Voonder', 'Research and Development', 'Tuck Tatton', '255-487-7574');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (415, 'Leenti', 'Product Management', 'Myer Carroll', '146-924-8888');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (416, 'Oyoyo', 'Sales', 'Catlin Pelcheur', '992-410-1263');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (417, 'Zoomdog', 'Sales', 'Margy Mapston', '806-580-6827');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (418, 'Izio', 'Support', 'Salomon Rawstron', '418-213-4091');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (419, 'Skipfire', 'Research and Development', 'Rafael Apps', '798-859-3867');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (420, 'Zoombeat', 'Training', 'Dilan Prewett', '337-345-2239');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (421, 'Kwimbee', 'Sales', 'Orton Thridgould', '171-997-4886');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (422, 'Abatz', 'Engineering', 'Neron Obbard', '275-239-8506');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (423, 'Muxo', 'Engineering', 'Gabi Isakovitch', '626-458-3173');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (424, 'Devcast', 'Marketing', 'Sibyl Bril', '219-805-8325');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (425, 'Youbridge', 'Support', 'Olenka Maybery', '994-569-7344');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (426, 'Zava', 'Services', 'Dusty MacWhan', '755-234-6228');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (427, 'Jabbertype', 'Training', 'Gaelan Seadon', '758-113-2673');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (428, 'Yotz', 'Legal', 'Farlay Diack', '959-421-1549');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (429, 'Rhyzio', 'Product Management', 'Malena Bracknell', '911-761-1892');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (430, 'Twinder', 'Services', 'Sarah Aikin', '807-635-6621');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (431, 'Roomm', 'Support', 'Cristionna Phillcox', '829-462-4857');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (432, 'Leexo', 'Marketing', 'Malissia Danilin', '919-331-1349');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (433, 'Skinder', 'Product Management', 'Tull GiacobbiniJacob', '404-174-6585');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (434, 'Youbridge', 'Business Development', 'Simonne Cuxon', '280-651-8970');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (435, 'Bubblebox', 'Accounting', 'Grant Plowes', '679-578-4610');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (436, 'Youbridge', 'Legal', 'Broddy Lillecrop', '741-946-0426');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (437, 'Avaveo', 'Business Development', 'Katuscha Guiel', '258-360-8806');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (438, 'Eazzy', 'Product Management', 'Demetris Hagstone', '748-844-8043');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (439, 'Pixope', 'Services', 'Giacobo Orts', '609-410-6761');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (440, 'Trupe', 'Support', 'Merrily Jehaes', '284-136-0458');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (441, 'Meetz', 'Marketing', 'Esta Goly', '503-629-2731');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (442, 'Shuffletag', 'Sales', 'Suzi Krochmann', '471-794-1224');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (443, 'Eazzy', 'Research and Development', 'Boyd Checo', '367-980-0153');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (444, 'Rooxo', 'Business Development', 'Maryrose Messingham', '996-549-3250');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (445, 'Topicware', 'Accounting', 'Barri Dewane', '538-339-9565');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (446, 'Viva', 'Legal', 'Kalinda Considine', '749-745-9616');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (447, 'Eazzy', 'Services', 'Evangelina Brayfield', '827-677-8733');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (448, 'Layo', 'Human Resources', 'Herbie Vedenisov', '991-736-1674');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (449, 'Trupe', 'Training', 'Mariya Elwel', '808-626-5632');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (450, 'Jayo', 'Marketing', 'Yank Muckleston', '949-438-5765');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (451, 'Jaloo', 'Human Resources', 'Ax Abram', '360-815-1904');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (452, 'Blogspan', 'Engineering', 'Lissie Litchmore', '147-492-9700');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (453, 'Shufflebeat', 'Research and Development', 'Lulu Bastin', '527-225-8942');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (454, 'Meezzy', 'Legal', 'Clemence Kloss', '779-752-4294');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (455, 'Livetube', 'Engineering', 'Drew Wylie', '818-868-2211');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (456, 'Eamia', 'Product Management', 'Clari Firidolfi', '155-146-5379');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (457, 'Kwilith', 'Training', 'Arri Pocke', '735-902-8427');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (458, 'Mymm', 'Legal', 'Brenn Bartoletti', '460-286-4576');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (459, 'Kazu', 'Marketing', 'Charmine Piggott', '565-586-9705');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (460, 'Gabvine', 'Engineering', 'Genna Humphrys', '879-451-9335');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (461, 'Voonte', 'Accounting', 'Allie Hawkeswood', '718-680-8837');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (462, 'Tekfly', 'Research and Development', 'Ulick Pyrke', '805-428-6050');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (463, 'Wikibox', 'Support', 'Joseph Stephen', '541-879-8959');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (464, 'Jamia', 'Business Development', 'Brook Menham', '526-821-8456');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (465, 'Tagchat', 'Engineering', 'Walliw Wegman', '463-793-2628');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (466, 'Kwimbee', 'Accounting', 'Roman Cana', '529-222-1334');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (467, 'Bubblebox', 'Legal', 'Maje Laroze', '967-392-9232');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (468, 'Devify', 'Accounting', 'Francklin Fetters', '642-206-4943');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (469, 'Realbuzz', 'Engineering', 'Chip Isson', '392-235-8523');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (470, 'Rhybox', 'Sales', 'Arlen Rosenstein', '721-535-4622');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (471, 'Divanoodle', 'Product Management', 'Mindy Grushin', '125-978-3956');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (472, 'Zoomcast', 'Training', 'Consolata Ollier', '265-226-9860');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (473, 'Twitterbridge', 'Accounting', 'Eugenia Bonevant', '910-313-2332');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (474, 'Mymm', 'Accounting', 'Clark Stallwood', '812-935-8026');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (475, 'Dabtype', 'Human Resources', 'Brandice Blight', '695-459-5571');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (476, 'Buzzshare', 'Human Resources', 'Marcie Caudray', '350-428-3037');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (477, 'Blogpad', 'Training', 'Osgood Filippazzo', '303-188-7692');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (478, 'Realcube', 'Engineering', 'Tonie Ketteridge', '922-827-1011');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (479, 'Pixope', 'Training', 'Bobbi Emerine', '690-276-4924');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (480, 'Trudeo', 'Training', 'Greg Benner', '801-388-9857');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (481, 'Jabbersphere', 'Human Resources', 'Pat Lawleff', '244-920-8381');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (482, 'Quinu', 'Research and Development', 'Kathryne Capelin', '896-120-7995');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (483, 'Youtags', 'Sales', 'Leonore Agron', '280-274-8858');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (484, 'Kazio', 'Human Resources', 'Brander Orris', '747-316-5290');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (485, 'Mudo', 'Support', 'Debbie de Clerk', '774-362-6068');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (486, 'Fliptune', 'Business Development', 'Ermin Prior', '156-471-1688');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (487, 'Brightbean', 'Legal', 'Felita Housam', '887-290-4072');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (488, 'Zava', 'Training', 'Valentino Boal', '914-109-7367');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (489, 'Gigashots', 'Business Development', 'Avie Keston', '462-854-6204');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (490, 'Dynava', 'Sales', 'Gideon Faithorn', '445-864-8065');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (491, 'Trudeo', 'Human Resources', 'Wilek Detoc', '419-112-3266');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (492, 'Viva', 'Marketing', 'Christabel Kwietek', '555-519-3675');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (493, 'Jaxworks', 'Research and Development', 'Anna-maria Mordon', '880-753-5561');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (494, 'Jetpulse', 'Sales', 'Reina Garrettson', '722-739-2336');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (495, 'Chatterpoint', 'Marketing', 'Addie Strahan', '573-567-6000');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (496, 'Linkbuzz', 'Research and Development', 'Eve Gatsby', '162-516-2680');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (497, 'Oyoyo', 'Training', 'Rosene Bradfield', '216-933-7777');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (498, 'Pixonyx', 'Research and Development', 'Calla Bocke', '164-810-7320');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (499, 'Kimia', 'Services', 'Kris Diter', '776-174-6767');
insert into SUPPLIER (SupplierID, SupplierName, Category, ContactName, Phone) values (500, 'Leenti', 'Support', 'Ciel Taphouse', '103-429-4075');
